
default_profile = "default"
display_name = "TiFlash"
http_port = 8123
listen_host = "0.0.0.0"
tcp_port = 9100
path = "${TIUP_DATA_DIR}/tiflash-0/data"
tmp_path = "${TIUP_DATA_DIR}/tiflash-0/tmp"


[flash]
service_addr = "${LOCALHOST}:3930"
tidb_status_addr = "${LOCALHOST}:10080"
[flash.flash_cluster]
cluster_manager_path = "${TIUP_HOME}/components/tiflash/v6.5.12/tiflash/flash_cluster_manager"
log = "${TIUP_DATA_DIR}/tiflash-0/log/tiflash_cluster_manager.log"
master_ttl = 60
refresh_interval = 20
update_rule_interval = 5
[flash.proxy]
config = "${TIUP_DATA_DIR}/tiflash-0/tiflash-learner.toml"

[logger]
count = 20
errorlog = "${TIUP_DATA_DIR}/tiflash-0/log/tiflash_error.log"
level = "debug"
log = "${TIUP_DATA_DIR}/tiflash-0/log/tiflash.log"
size = "1000M"

[profiles]
[profiles.default]
load_balancing = "random"
max_memory_usage = 0
use_uncompressed_cache = 0
[profiles.readonly]
readonly = 1

[quotas]
[quotas.default]
[quotas.default.interval]
duration = 3600
errors = 0
execution_time = 0
queries = 0
read_rows = 0
result_rows = 0

[raft]
pd_addr = "${LOCALHOST}:2379"

[status]
metrics_port = 8234

[users]
[users.default]
password = ""
profile = "default"
quota = "default"
[users.default.networks]
ip = "::/0"
[users.readonly]
password = ""
profile = "readonly"
quota = "default"
[users.readonly.networks]
ip = "::/0"
